import { QualityGoal } from "@/types";

export const THEMES = [
  "Viagem no tempo",
  "Inteligência artificial rebelde",
  "Ficção científica espacial",
  "Distopia futurista",
  "Alienígenas e invasão da Terra",
  "Mundos paralelos e Multiverso",
  "Cyberpunk e implantes",
  "Realidade virtual simulada",
  "Clonagem humana",
  "Mutações genéticas",
  "Colonização de Marte",
  "Ciberataques e hackers",
  "Apocalipse zumbi",
  "Terror em cabana isolada",
  "Casa mal-assombrada",
  "Fantasmas e possessão",
  "Monstro gigante ou Godzilla",
  "Investigação criminal",
  "Mistério de assassinato",
  "Conspiração governamental",
  "Serial killer à solta",
  "Terror psicológico",
  "Seitas secretas",
  "Jogos mortais de sobrevivência",
  "Slasher de acampamento",
  "Vampiros contra lobisomens",
  "Bruxaria histórica",
  "Criaturas das profundezas do mar",
  "Sobrevivência na natureza",
  "Vingança pessoal",
  "Super-heróis e quadrinhos",
  "Assalto perfeito",
  "Aventura arqueológica e tesouros",
  "Samurais e artes marciais",
  "Pirataria e mares",
  "Espionagem internacional",
  "Corrida mortal de carros",
  "Herói aposentado que volta à ativa",
  "Resgate de reféns",
  "Fuga da prisão",
  "Caça ao tesouro moderno",
  "Mercenários em missão secreta",
  "Perseguição na estrada",
  "Guerra de cartéis de drogas",
  "Viagem de autoconhecimento",
  "Romance proibido",
  "Comédia romântica",
  "Drama tribunal e julgamentos",
  "Doença terminal e superação",
  "Reencarnação e destino",
  "Colégio e amadurecimento",
  "Crise de meia-idade",
  "Casamento em crise",
  "Histórias de imigração",
  "Relação difícil entre pai e filho",
  "Redenção de um viciado",
  "Gêmeos trocados",
  "Amor não correspondido",
  "Perda e luto familiar",
  "Amizade testada pelo tempo",
  "Magia e mundo fantasiado",
  "Guerra medieval",
  "Faroeste clássico",
  "Gangues e máfia",
  "Guerra moderna ou histórica",
  "Corrupção policial",
  "Gladiadores romanos",
  "Império Egípcio e múmias",
  "Cangaceiros do sertão",
  "Segunda Guerra Mundial",
  "Revolução Francesa",
  "Golpe de Estado",
  "Esporte underdog (superação)",
  "Dança e música",
  "Desastres naturais",
  "Zumbis corporativos ou sátira",
  "Troca de corpos",
  "Viagem de carro com amigos",
  "Cachorro ou animal herói",
  "Festa que sai do controle",
  "Paródia de filmes famosos",
  "Fim do mundo por meteoro",
  "Naufrágio em ilha deserta",
  "Animação de brinquedos vivos",
  "Biopic de músico famoso",
  "Chef de cozinha sob pressão",
  "Bastidores do cinema",
  "Concurso de talentos",
  "Alpinismo extremo",
  "Surgimento de uma nova religião",
  "Epidemia global",
  "Reality show mortal",
  "Mistério em um train",
  "Inverno eterno",
  "Previsão do futuro",
  "Batalhas de rap ou rimas",
  "Maldição de família",
  "Bancos de dados biológicos",
  "Sequestro internacional",
  "Vida de circo antigo"
];

export const GOALS: QualityGoal[] = [
  { id: 'excellent', label: 'Excelente (8.0 ou mais)', min: 8.0, max: 10.0 },
  { id: 'very_good', label: 'Muito Bom (7.0 a 7.9)', min: 7.0, max: 7.9 },
  { id: 'average', label: 'Mediano (6.0 a 6.9)', min: 6.0, max: 6.9 },
  { id: 'weak', label: 'Fraco (5.0 a 5.9)', min: 5.0, max: 5.9 },
  { id: 'bad', label: 'Ruim (Abaixo de 5.0)', min: 0.0, max: 4.9 },
];